version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  groups:
    rubocop:
      patterns:
        - "rubocop*"
    solid-rails:
      patterns:
        - "solid_*"
    test-tooling:
      patterns:
        - "faker"
        - "factory_bot*"
        - "shoulda*"
        - "capybara*"
        - "cuprite"
        - "database_cleaner*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
