Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: ["describe", "it", "context"]
  Exclude:
    - "spec/**/*.rb"
