inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-factory_bot
  - rubocop-capybara

# CI fix: https://github.com/rubocop/rubocop/issues/9832#issuecomment-873398952
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'lib/tasks/*.rake'
    - 'bin/*'
    - 'config/puma.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

# Only if not using I18n
Rails/I18nLocaleTexts:
  Enabled: false

# Ease up a bit on the default restrictions
RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10
