GET {{host}}/search
Accept: application/json

###

GET {{host}}/search?q=docker
Accept: application/json

###

GET {{host}}/search?q=heroku
Accept: application/json

###

GET {{host}}/search?q=podcast
Accept: application/json

###

GET {{host}}/search?q=personal%20finance
Accept: application/json

###

GET {{host}}/search?q=
Accept: application/json

###

GET {{host}}/search?q=zzzzzzzzz
Accept: application/json
