# frozen_string_literal: true

# Be sure to restart your server when you modify this file.

# Content Security Policy (CSP)
# ==============================
# CSP is the browser's last line of defence against XSS. If an injected script
# ever lands in the app (via a visit URL, a gem vulnerability, etc.), CSP is what
# prevents it from executing or exfiltrating data.
#
# This file was originally generated by Rails with everything commented out.
# It was left that way because Chartkick injects inline <script> tags, and Turbo
# uses inline handlers, both of which conflict with a strict script-src 'self'.
# The solution is nonce-based allowlisting — Rails generates a nonce per session,
# stamps it on every script tag it renders, and declares it in the CSP header.
# The browser only executes scripts whose nonce matches the header.
#
# Directive notes:
#
#   script-src :self
#     No :unsafe_inline — nonce covers Chartkick and importmap scripts instead.
#     Chartkick 5.2+ reads content_security_policy_nonce automatically (nonce: true
#     is the default in its helper). importmap-rails also stamps the nonce on every
#     <script type="importmap"> and <script type="module"> it generates.
#
#   style-src :self, :unsafe_inline
#     Tailwind's JIT output includes inline styles that cannot easily be nonced,
#     so unsafe-inline is required here. This is a known Tailwind limitation.
#
#   img-src :self, :data, :blob
#     :data — base64 data URIs used by Chart.js for chart export/download.
#     :blob — blob URLs used by some chart interactions.
#
#   object-src :none
#     Disables Flash and other legacy plugin content entirely.
#
# Nonce generator — WHY session-based, not per-request SecureRandom:
#   Using SecureRandom.base64(16) (a fresh nonce on every request) breaks
#   Turbo Drive. After login, Turbo navigates to /visits via an XHR fetch rather
#   than a full page load. The browser keeps enforcing the sign-in page's CSP
#   (nonce N0), but the body scripts in the /visits response carry the new
#   request's nonce (N1). N0 != N1 → browser blocks Chartkick scripts → charts
#   never render. Session-bound nonces are consistent across all Turbo Drive
#   navigations within a session, so the nonce always matches.
#
# See the Securing Rails Applications Guide for more information:
# https://guides.rubyonrails.org/security.html#content-security-policy-header

Rails.application.configure do
  config.content_security_policy do |policy|
    policy.default_src :self
    policy.script_src  :self
    policy.style_src   :self, :unsafe_inline
    policy.img_src     :self, :data, :blob
    policy.font_src    :self
    policy.object_src  :none
    policy.connect_src :self
  end

  # Session-based nonce — consistent within a session so Turbo Drive navigations
  # always match the original page's CSP. See comment block above for details.
  config.content_security_policy_nonce_generator = ->(request) { request.session.id.to_s }
  config.content_security_policy_nonce_directives = %w[script-src]
end
